Updated Upstream
SlimeTraditionalTranslation/AlchimiaVitae pull request #6
Opened 2021-08-09 22:42 UTC by weiii-joe

DEV - 8
 
更新日記:
添加藥水持續時間和等級的配置選項

2021-08-09 22:58 UTC, weiii-joe commented on src/main/java/me/apeiros/alchimiavitae/setup/Items.java
> +            "&d注入只能金,鐵, 鑽石, 或獄髓錠,", "&弓與弩也可以在這個祭壇上使用");
我該翻哪個 嗯...我先去睡了!
注入只能 還是 只能注入

2021-08-10 08:44 UTC, xMikux requested changes

2021-08-10 08:44 UTC, xMikux commented on src/main/java/me/apeiros/alchimiavitae/setup/Items.java
> +            "&d只能注入金,鐵, 鑽石, 或獄髓錠,", "&弓與弩也可以在這個祭壇上使用");
材質空格 與錠去掉

2021-08-10 09:16 UTC, xMikux approved these changes

2021-08-10 09:19 UTC, merged